<a href="https://colab.research.google.com/github/tharak-bairneni/coding-practice/blob/main/Tharak_Bairneni_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

TASK 1 — Load Dataset & Preview

In [4]:
import pandas as pd

# Direct download link
url = "https://drive.google.com/uc?id=1Mlu9r3afSGz5_02Y3wDJoQLpXszQXaIU"

# Load dataset with order_id as index
df = pd.read_csv(url, index_col="order_id")

# Display first 5 rows
print("First 5 rows:")
display(df.head())

# Display last 5 rows
print("Last 5 rows:")
display(df.tail())

First 5 rows:

          customer_name   product  quantity  unit_price  order_date     status
order_id
1001      Alice Johnson    Laptop       1.0     85000.0  2024-01-15  delivered
1002          Bob Smith     Mouse       3.0       499.0  2024-01-16    pending
1003        Carol White   Monitor       2.0     15000.0         NaN  delivered
1004         Dave Brown  Keyboard       NaN      1200.0  2024-01-18  cancelled
1005          Eva Green    Laptop       1.0     85000.0  2024-01-19  delivered

Last 5 rows:

         customer_name   product  quantity  unit_price  order_date     status
order_id
1016       Paul Harris     Mouse       6.0       499.0  2024-01-30    pending
1017      Quinn Martin   Monitor       NaN     14500.0  2024-01-31  delivered
1018       Rachel King    Laptop       1.0     85000.0         NaN  delivered
1019        Sam Wright  Keyboard       3.0      1200.0  2024-02-01  cancelled
1020        Tina Baker   USB Hub       2.0       799.0  2024-02-02    pending

TASK 2 — Structural Inspection

In [3]:
# Basic structure
print("Dataset Info:")
df.info()

print("\nShape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 1001 to 1020
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_name  20 non-null     object
 1   product        20 non-null     object
 2   quantity       16 non-null     float64
 3   unit_price     20 non-null     float64
 4   order_date     16 non-null     object
 5   status         20 non-null     object
dtypes: float64(2), object(4)
memory usage: 1.1+ KB

Shape: (20, 6)

Missing Values:
customer_name    0
product          0
quantity         4
unit_price       0
order_date       4
status           0
dtype: int64

1️⃣ How many rows and columns? The dataset has df.shape[0] rows and df.shape[1] columns. (20 rows and 6 columns)

2️⃣ Missing values? Use df.isnull().sum() output to list which columns have null values and how many.

3️⃣ Column needing type conversion? The order_date column needs conversion from object to datetime. Use:pd.to_datetime(df["order_date"])

In [11]:
print("rows", df.shape[0])
print("columns", df.shape[1])

rows 20
columns 6

In [12]:
df.isnull().sum()

customer_name    0
product          0
quantity         4
unit_price       0
order_date       4
status           0
dtype: int64

In [13]:
pd.to_datetime(df["order_date"])

order_id
1001   2024-01-15
1002   2024-01-16
1003          NaT
1004   2024-01-18
1005   2024-01-19
1006   2024-01-20
1007   2024-01-21
1008          NaT
1009   2024-01-23
1010   2024-01-24
1011   2024-01-25
1012   2024-01-26
1013          NaT
1014   2024-01-28
1015   2024-01-29
1016   2024-01-30
1017   2024-01-31
1018          NaT
1019   2024-02-01
1020   2024-02-02
Name: order_date, dtype: datetime64[ns]

TASK 3 — Statistical Summary

In [6]:
# Summary statistics
summary = df.describe()
display(summary)

# Median unit_price
median_price = df["unit_price"].median()
print("Median unit_price:", median_price)

        quantity    unit_price
count  16.000000     20.000000
mean    2.437500  20224.600000
std     1.504161  33573.389607
min     1.000000    499.000000
25%     1.000000    799.000000
50%     2.000000   2500.000000
75%     3.000000  14625.000000
max     6.000000  85000.000000

Median unit_price: 2500.0

1️⃣ Median unit_price
The median unit_price is [value from output].

2️⃣ Is unit_price skewed?
If the mean is higher than the median → Right-skewed.
If the mean is lower than the median → Left-skewed.

In [7]:
df["order_date"] = pd.to_datetime(df["order_date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 1001 to 1020
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_name  20 non-null     object
 1   product        20 non-null     object
 2   quantity       16 non-null     float64
 3   unit_price     20 non-null     float64
 4   order_date     16 non-null     datetime64[ns]
 5   status         20 non-null     object
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 1.1+ KB